config/routes.rb
Rails.application.routes.draw do

  get 'payment_notification/create'

  get 'site/about'
  get 'site/contact'

 
  get '/about' => 'site#about' 
  get '/contact' => 'site#contact'

  get '/admin' => 'user#admin_login'
  get '/logout' => 'user#logout'
  get '/signedinuserprofile' => 'profiles#signedinuserprofile'
  
  resources :profiles
  devise_for :users

  resources :products
  resources :order_items
  resource :carts, only: [:show] 
  resource :payments, only: [:show]
  resource :thankyous, only: [:show]
  delete '/carts' => 'carts#destroy'
  get '/carts/index' => 'carts#index'
  get '/thankyous/index' => 'thankyous#index'
  
  #resources :payment_notification, only: [:create]
  get '/profile/show'=> 'profile#show'
  
# devise_for "users", :skip => [:registrations]
#  as :user do
#   get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_regsitration'
#   put 'users' => 'devise/registrations#update', :as => 'user_registration'
#  end 
  root 'site#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_many :order
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]


  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
    session[:order] = Order.find(session[:order_id])
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    
  end

  # GET /profiles/new
  def new
   @profile = Profile.new
   @profile.user_id = current_user.id
    
    respond_to do |format|
     format.html # new.html.erb
     format.json { render json: @profile }
   end
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def signedinuserprofile
    profile = Profile.find_by_user_id(current_user.id)
    if profile.nil? 
      redirect_to"/profiles/new"
      

  else
    @profile = Profile.find_by_user_id(current_user.id)
    redirect_to"/profiles/#{@profile.id}"
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:firstname, :lastname, :address, :user_id)
    end
    
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="yellow-surrounding-box">
  <div class="field", style = "font-size: 20px; margin-top: 30px;">
    <%= form.label :firstname %>
    <%= form.text_field :firstname, id: :profile_firstname, class: "edit-input" %>
  </div>

  <div class="field", style = "font-size: 20px;">
    <%= form.label :lastname %>
    <%= form.text_field :lastname, id: :profile_lastname, class: "edit-input" %>
  </div>

  <div class="field", style ="margin-left: 10px; font-size: 20px">
    <%= form.label :address %>
    <%= form.text_field :address, id: :profile_address, class: "edit-input" %>
  </div>


  <div class="fielduser">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :profile_user_id %>
  </div>

  <%= link_to "Change your password", edit_user_registration_path %>
  
  <div class="actions", style = "font-size:20px; margin-top: 30px;">
    <%= form.submit %>
  </div>
</div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<div class="yellow-surrounding-box">

<% if current_user && current_user.admin? %>
 <%= link_to 'Show', @profile %> |
 <%= link_to 'Back', profiles_path %>
<% end %>

<%= render 'form', profile: @profile %>
</div>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profiles</h1>

<div class="yellow-surrounding-box">
  
<table>
  <thead>
    <tr style = "font-size: 20px;">
      <th style = "padding: 10px;">Firstname</th>
      <th style = "padding: 10px;">Lastname </th>
      <th style = "padding: 10px;"> Address</th>
      <th> User ID </th>
      <th colspan="4"></th>
    </tr>
  </thead>
 
  <tbody>
  
    <% @profiles.each do |profile| %>
    
      <tr style = "color:black; font-style:arial;">
        <td ><%= profile.firstname %></td>
        <td><%= profile.lastname %></td>
        <td><%= profile.address %></td>
        <td><%= profile.user %></td>
        <td><%= profile.user %></td>
        <% @orders.each do |order| %>
        <td ><%= order.subtotal %></td>
        
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      
      </tr>
   </div>
  </tbody>
</table>
</div>
<br>
 

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<div class="yellow-surrounding-box">
  
<%= render 'form', profile: @profile %>
<% if current_user && current_user.admin? %>
 <%= link_to 'Back', profiles_path %>
<% end %>

</div>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<div class="yellow-surrounding-box">

<p>
  <strong>Firstname:</strong>
  <%= @profile.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @profile.lastname %>
</p>

<p>
  <strong>Address:</strong>
  <%= @profile.address %>
</p>

<% if current_user && current_user.admin? %>
 <p>
  <strong>User:</strong>
  <%= @profile.user %>
 </p>
<% end %>

 <%= link_to 'Edit', edit_profile_path(@profile) %> 
<% if current_user && current_user.admin? %>
 <%= link_to 'Back', profiles_path %>
<% end %>

</div>