config/routes.rb
Rails.application.routes.draw do

  get 'payment_notification/create'

  get 'site/about'
  get 'site/contact'

 
  get '/about' => 'site#about' 
  get '/contact' => 'site#contact'

  get '/admin' => 'user#admin_login'
  get '/logout' => 'user#logout'
  get '/signedinuserprofile' => 'profiles#signedinuserprofile'
  
  resources :profiles
  devise_for :users

  resources :products
  resources :order_items
  resource :carts, only: [:show] 
  resource :payments, only: [:show]
  resource :thankyous, only: [:show]
  delete '/carts' => 'carts#destroy'
  get '/carts/index' => 'carts#index'
  get '/thankyous/index' => 'thankyous#index'
  
  #resources :payment_notification, only: [:create]
  get '/profile/show'=> 'profile#show'
  
# devise_for "users", :skip => [:registrations]
#  as :user do
#   get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_regsitration'
#   put 'users' => 'devise/registrations#update', :as => 'user_registration'
#  end 
  root 'site#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	
	def show
			@order_items = current_order.order_items
	end

	
	def index
		session.delete(:order_id)

	end

end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/carts/_cart_item.html.erb
<div>
		<div>
		    <h5>Order Total: <%="#{current_order.subtotal}"%></h4>
		    <%= button_to 'Go to checkout', payments_path, :method => :get %>
		    <%= link_to 'Empty Cart', thankyous_index_url(@thankyous), method: :get, data: { confirm: 'Are you sure?' } %>
		</div>
		<h4><strong><u>Order Summary</u></strong></h4>
		
		<div class="yellow-surrounding-box">
		<% if @order_items.size>0 %>
			<% @order_items.each do |item| %>

				<div class="table">
					<div class="row">
					<div class="col-sm-8">
						
					<h6><strong><u><%= item.product.product%></u></strong></h6>
					<h6>€<%= item.product.description%></h6>
					<h6>€<%= item.product.price%></h6>
				</div>
				<div class="col-sm-4">
					<div class="pull-right">
					<%= form_for(item, remote: true) do |f| %>
						<%= f.hidden_field :product_id, value: item.product.id %>
					
						<div class="form-group">
							<%= f.text_field :quantity, value: item.quantity.to_i, min: 1, :maxlength=>"7" %>
						</div>
						<div class="btn-group">
							<%= f.submit "Update" %>
							<%= button_to "Delete", item, method: :delete, remote: true, data: {confirm: "Are you sure you want to remove the Item"}  %>
						</div>
						<h5>€<%= item.total_price %></h5>
					<% end %>
					</div>
				</div>
			</div>
		</div>
		</div>
	</div>
	<% end %>

<% else %>
	
<% end %>

app/views/carts/create.js.erb
<% if @order.errors.any? || @order_item.errors.any? %>
	alert("Invalid")
<% else %>
	$(".order_item").html("<%= escape_javascript(render 'payments/pay_now') %>")
<% end %>

app/views/carts/destroy.js..erb
	$(".cart").html("<%= escape_javascript(render 'layouts/cart') %>")

app/views/carts/index.html.erb
<h3> The cart is Empty</h3>
<div class="yellow-surrounding-box">
		<p> Please add some products to proceed</p>
			<%= link_to 'Continue Shopping', :controller => :products %>
			</div>
		<% end %>

app/views/carts/show.html.erb
<h1>You Cart</h1>
<p>Find the summary of the cart products below: </p>
    <div class="yellow-surrounding-box">

<% if @order_items.size>0 %>
                <div class="cart_item">
	            <%= render "carts/cart_item" %>
	  <% else %>
	  <h3> The cart is Empty</h3>
		<p> Please add some products to proceed</p>
			<%= link_to 'Continue Shopping', :controller => :products %>
		<% end %>
 </div>
	  <div>
	    <% if current_user && current_user.admin? %>
   <%= link_to 'New Product', new_product_path %>
   <% end %>
 </div>
</div>

</br>