config/routes.rb
Rails.application.routes.draw do

  get 'payment_notification/create'

  get 'site/about'
  get 'site/contact'

 
  get '/about' => 'site#about' 
  get '/contact' => 'site#contact'

  get '/admin' => 'user#admin_login'
  get '/logout' => 'user#logout'
  get '/signedinuserprofile' => 'profiles#signedinuserprofile'
  
  resources :profiles
  devise_for :users

  resources :products
  resources :order_items
  resource :carts, only: [:show] 
  resource :payments, only: [:show]
  resource :thankyous, only: [:show]
  delete '/carts' => 'carts#destroy'
  get '/carts/index' => 'carts#index'
  get '/thankyous/index' => 'thankyous#index'
  
  #resources :payment_notification, only: [:create]
  get '/profile/show'=> 'profile#show'
  
# devise_for "users", :skip => [:registrations]
#  as :user do
#   get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_regsitration'
#   put 'users' => 'devise/registrations#update', :as => 'user_registration'
#  end 
  root 'site#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def index
    @order_items = current_order.order_items
  end
 def show

    @profile = Profile.find_by_user_id(current_user.id)
      
 end
end

app/helpers/payment_helper.rb
module PaymentHelper
end

app/views/payments/_pay_now.html.erb
<p>We are extremely happy that you are making this doation through Focus Ireland. Please fill in the below details</p>
 <form>
     <form action="thankyous/show.html.erb">
      <input type="text" class="form-control"  name="name" placeholder="Name" required>
      <input type="text" class="form-control"  name="phone" placeholder="Telephone" required>
      <input type="text" class="form-control" name="email" placeholder="Email" required>
      
      <input type="Submit">
  <div>
		<h5>Price: €<%= "#{current_order.subtotal}"%></h5>

		</div>
		</form>

	     <div>
	      <p>We appreciate your kind donation! Click pay now to complete your order </p>
	 <%= button_to 'Pay Now', thankyous_path, :method => :get %>

	  </div>

app/views/payments/show.html.erb
<h1>Payment</h1>
<body>
    <div class="yellow-surrounding-box">
                <div class="pay_now">
	            <%= render "payments/pay_now" %>
	           </div>
	  </div>
	  <div>
	    <% if current_user && current_user.admin? %>
   <%= link_to 'New Product', new_product_path %>
   <% end %>
</div>
</body>
<br>